export const jsonFileExtensions = {
  "application/pdf": "pdf",
  "audio/flac": "flac",
  "audio/x-m4a": "m4a",
  "audio/mpeg": "mp3",
  "audio/mp3": "mp3",
  "audio/ogg": "oga",
  "audio/wav": "wav",
  "audio/webm": "weba",
  "image/avif": "avif",
  "image/bmp": "bmp",
  "image/gif": "gif",
  "image/x-icon": "ico",
  "image/jpeg": "jpeg",
  "image/png": "png",
  "image/svg+xml": "svg",
  "image/tiff": "tif",
  "image/webp": "webp",
  "image/x-xbitmap": "xbm",
  "text/css": "css",
  "text/csv": "csv",
  "text/html": "html",
  "text/plain": "txt",
  "video/mp4": "mp4",
  "video/mpeg": "mpeg",
  "video/ogg": "ogm",
  "video/webm": "webm"
};
